In [1]:
import numpy as np

# Convert a 1-D array into a 2-D array with 3 rows.

In [2]:
arr1 = np.array([0,1,2,3,4,5,6,7,8])
arr1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Replace all odd numbers in the given array with -1

In [3]:
arr2 = np.array([0,1,2,3,4,5,6,7,8])

odd = np.where(arr2 % 2!=0)

arr2[odd]=-1

print(arr2)

[ 0 -1  2 -1  4 -1  6 -1  8]


# Find the positions of elements in x where its value is more than its corresponding element in y, and elements in x where its value is equals to its corresponding element in y.

In [4]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

X = np.where(x>y)[0]
Y = np.where(x==y)[0]

print(X)
print(Y)

[1 2 4 5 6 7 8 9]
[0]


# Extract the first four columns of this 2-D array.

In [5]:
arr4 = np.arange(100).reshape(5,-1)
col = arr4[:,:4]
print(col)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


# Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)

In [6]:
random = np.random.randint(30,41,size=10)
print(random)

[31 37 40 35 33 30 36 38 38 36]


In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

B = np.array([[7, 8, 10],
              [4, 5, 6],
              [1, 2, 3]])

C = A+B
E = A-B
print(C)

print(E)
print()

a = np.sum(A)
b = np.sum(B, axis = 0)
c = np.sum(C, axis = 1)
print(a)
print(b)
print(c)
print()

D = np.dot(A,B)
print(D)
print()

F = np.sort(C,axis=None) 
print(F)
print()

G = np.transpose(E)
print(G)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]

46
[12 15 19]
[31 30 31]

[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]

[ 8  8  8 10 10 10 12 13 13]

[[-6  0  6]
 [-6  0  6]
 [-7  0  7]]
